<a href="https://colab.research.google.com/github/sakruthi/python/blob/master/28_june_19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to oop in ptython:-  
### **one of the popular approach to solve a programming problem by creating an objects. This is known as Object Oriented Programming.
### An object has two characterstics:
#### 1.attributes(name,age,colour)  
#### 2.behaviour(learn,study,singing,dance)

### **In Python, the concept OOP follow these things:    
#### 1.Inheritance      
#### 2.Encapsulation     
#### 3.Ploymorphism

### **Class: A class is blueprint for the object or logical entity

###**Object:  Blue print of class or instance of the class or physical entity

In [0]:
def test():
  print('test()for function')
  return
test()

test()for function


In [0]:
class demo:
  def test(self):
    print("test()for the class and method")
    return
obj=demo()
obj.test()

test()for the class and method


In [0]:
class demo1:
  def fact(self,n):
    #return the factioral
    fact=1
    while(n!=0):
      fact=fact*n
      n=n-1
    return fact
p1=demo1()
print(p1.fact(5))#120

120


In [0]:
class demo2:
  a=0,b=0
  def accept(self,p1,p2):

In [0]:
class demo2:
  def __init__(self,p1,p2):
    self.p1=p1
    self.p2=p2
    
  def add(self,p1,p2):
     return p1+p2
  
  
c1=demo2(10,20)
print(c1.add(100,200))

300


In [0]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [0]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)                         
print(array.dtype)

(4,)
int64


In [0]:
lst=[1.0,2.4,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np

(2, 3)


In [0]:
#re-shape the given array
#numpy.reshape(arrayname,reshape,order='c')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
#append some data -- horizontally
#hstack(array1,array2) --- will be automatically arranged in vertically
  a1=np.array([1,2,3])
  a2=np.array([4,5,6])
  print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [0]:
#generate random number 

In [0]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]])

In [0]:
#np.ones(shape,dtype=float,order='c')
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [0]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [0]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [0]:
#indexing and slicing of numpy
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row:",a1[:,1])

second row: [2 5]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print("silcing last column:",a1[:,2])

second row: [3 6]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[0])

first row: [1 2 3]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[1,:1])

first row: [4]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[1][1])

first row: 5


In [0]:
a1=np.random.normal(5,1,10)
print(a1)

[5.8243031  6.56414729 5.42744327 4.14707741 5.44202488 6.04675136
 4.40826988 4.07335838 4.64374654 5.25013545]


In [0]:
#Some math Operation on givrn random numbers
#Min--returns the least number
#Max--returns the Large number
#Mean--Mean
#Median--Median
#gd--gaussian distribution
a1=np.random.normal(5,1,10)
print(a1)
print("Min value=",np.min(a1))
print("Max value=",np.max(a1))
print("Mean value=",np.mean(a1))
print("Median value=",np.median(a1))

[4.86729913 4.91428698 5.93847182 4.48895283 5.69309798 5.19842861
 4.32750932 4.55570249 6.54522096 5.68160803]
Min value= 4.327509321317576
Max value= 6.545220964863946
Mean value= 5.221057815724299
Median value= 5.0563577929842225


In [0]:
#multiply of 1d arrays
#numpy.dot(x,y)--

c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [0]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [0]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

### Pandas Basics:-       
       
 Python is one of the popular programming language for data analysis<br>    
Python is offering the Lib called Pandas used for importing and analysing pretty much faster and easier also            
Pandas DataFrames        
    
    Data Analysis with Python

In [0]:
import pandas as pd
dict={"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],"EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],"MobileNumber":[999,888,777,888,777,999],"Address":["Hyd","Hyd","Hyd","Hyd","Hyd","Hyd"],}
b=pd.DataFrame(dict)
print(b)

     Name           EmailID  MobileNumber Address
0    Anil    anil@gmail.com           999     Hyd
1   Akhil   akhil@gmail.com           888     Hyd
2  Dinesh  dinesh@gmail.com           777     Hyd
3  Harsha  harsha@gmail.com           888     Hyd
4    Ajay    ajay@gmail.com           777     Hyd
5  Kranth  kranth@gmail.com           999     Hyd


In [0]:
#super market.csv-Analysis (which product having higher 5 of selling)
#which products having least selling %
import pandas as pd
products=pd.read_csv('FileName.csv')
print(products)

FileNotFoundError: ignored